name: kelompoktwoo
description: "Project Flutter SMK N 10 Semarang"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0-beta

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.1
  print_bluetooth_thermal: ^1.1.0
  # open_settings: ^2.0.2
  permission_handler: ^11.3.1
  flutter_esc_pos_utils: ^1.0.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.19.0
  dio: ^5.4.3+1
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_remote_config: ^5.1.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  firebase_crashlytics: ^4.1.0
  sentry_flutter: ^8.2.0
  flutter_uxcam: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icons/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
